// <auto-generated />
using System;
using DynamicForms_WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynamicForms_WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528180130_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DynamicForms_WebAPI.Data.FieldRolePermission", b =>
                {
                    b.Property<int>("FieldPermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FieldPermissionId"));

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<string>("PermissionLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("FieldPermissionId");

                    b.HasIndex("FieldId");

                    b.ToTable("FieldRolePermissions");

                    b.HasData(
                        new
                        {
                            FieldPermissionId = 1,
                            FieldId = 1,
                            PermissionLevel = "Write",
                            RoleId = 1
                        },
                        new
                        {
                            FieldPermissionId = 2,
                            FieldId = 2,
                            PermissionLevel = "Write",
                            RoleId = 1
                        },
                        new
                        {
                            FieldPermissionId = 3,
                            FieldId = 3,
                            PermissionLevel = "Write",
                            RoleId = 1
                        },
                        new
                        {
                            FieldPermissionId = 4,
                            FieldId = 4,
                            PermissionLevel = "Write",
                            RoleId = 1
                        },
                        new
                        {
                            FieldPermissionId = 5,
                            FieldId = 1,
                            PermissionLevel = "Write",
                            RoleId = 2
                        },
                        new
                        {
                            FieldPermissionId = 6,
                            FieldId = 2,
                            PermissionLevel = "Write",
                            RoleId = 2
                        },
                        new
                        {
                            FieldPermissionId = 7,
                            FieldId = 3,
                            PermissionLevel = "Write",
                            RoleId = 2
                        },
                        new
                        {
                            FieldPermissionId = 8,
                            FieldId = 4,
                            PermissionLevel = "Read",
                            RoleId = 2
                        },
                        new
                        {
                            FieldPermissionId = 9,
                            FieldId = 1,
                            PermissionLevel = "Write",
                            RoleId = 3
                        },
                        new
                        {
                            FieldPermissionId = 10,
                            FieldId = 2,
                            PermissionLevel = "Write",
                            RoleId = 3
                        },
                        new
                        {
                            FieldPermissionId = 11,
                            FieldId = 3,
                            PermissionLevel = "Write",
                            RoleId = 3
                        },
                        new
                        {
                            FieldPermissionId = 12,
                            FieldId = 4,
                            PermissionLevel = "Hidden",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("DynamicForms_WebAPI.Data.Form", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FormId");

                    b.ToTable("Forms");

                    b.HasData(
                        new
                        {
                            FormId = 1,
                            CreatedAt = new DateTime(2026, 5, 28, 18, 1, 29, 709, DateTimeKind.Utc).AddTicks(3769),
                            CreatedBy = 1,
                            FormName = "Employee Onboarding Form"
                        });
                });

            modelBuilder.Entity("DynamicForms_WebAPI.Data.FormField", b =>
                {
                    b.Property<int>("FieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FieldId"));

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("ValidationRules")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FieldId");

                    b.HasIndex("FormId");

                    b.ToTable("FormFields");

                    b.HasData(
                        new
                        {
                            FieldId = 1,
                            FieldName = "Full Name",
                            FieldType = "Text",
                            FormId = 1,
                            IsRequired = true,
                            ValidationRules = "{\"minLength\": 2, \"maxLength\": 50}"
                        },
                        new
                        {
                            FieldId = 2,
                            FieldName = "Joining Date",
                            FieldType = "Date",
                            FormId = 1,
                            IsRequired = true
                        },
                        new
                        {
                            FieldId = 3,
                            FieldName = "Remote Worker",
                            FieldType = "Checkbox",
                            FormId = 1,
                            IsRequired = false
                        },
                        new
                        {
                            FieldId = 4,
                            FieldName = "Approved Salary",
                            FieldType = "Number",
                            FormId = 1,
                            IsRequired = true,
                            ValidationRules = "{\"min\": 1000}"
                        });
                });

            modelBuilder.Entity("DynamicForms_WebAPI.Data.FormRolePermission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("PermissionId");

                    b.ToTable("FormRolePermissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            FormId = 1,
                            IsVisible = true,
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 2,
                            FormId = 1,
                            IsVisible = true,
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 3,
                            FormId = 1,
                            IsVisible = true,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("DynamicForms_WebAPI.Data.FormSubmission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<string>("ResponseData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubmittedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SubmissionId");

                    b.ToTable("FormSubmissions");
                });

            modelBuilder.Entity("DynamicForms_WebAPI.Data.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("DynamicForms_WebAPI.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            PasswordHash = "password123",
                            RoleId = 1,
                            Username = "admin_bob"
                        },
                        new
                        {
                            UserId = 2,
                            PasswordHash = "password123",
                            RoleId = 2,
                            Username = "manager_alice"
                        },
                        new
                        {
                            UserId = 3,
                            PasswordHash = "password123",
                            RoleId = 3,
                            Username = "user_charlie"
                        });
                });

            modelBuilder.Entity("DynamicForms_WebAPI.Data.FieldRolePermission", b =>
                {
                    b.HasOne("DynamicForms_WebAPI.Data.FormField", "FormField")
                        .WithMany("FieldRolePermissions")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormField");
                });

            modelBuilder.Entity("DynamicForms_WebAPI.Data.FormField", b =>
                {
                    b.HasOne("DynamicForms_WebAPI.Data.Form", "Form")
                        .WithMany("FormFields")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("DynamicForms_WebAPI.Data.User", b =>
                {
                    b.HasOne("DynamicForms_WebAPI.Data.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DynamicForms_WebAPI.Data.Form", b =>
                {
                    b.Navigation("FormFields");
                });

            modelBuilder.Entity("DynamicForms_WebAPI.Data.FormField", b =>
                {
                    b.Navigation("FieldRolePermissions");
                });

            modelBuilder.Entity("DynamicForms_WebAPI.Data.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
